default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: grouplr_dev

test:
  <<: *default
  database: grouplr_test

production:
  <<: *default
  database: grouplr_prod
  username: groupie
  password: <%= ENV['BOILER_DATABASE_PASSWORD'] %>
